### ISSUE TITLE
Freeze on playlist resizing

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nulloy/nulloy#180]
![nulloy-freeze-after-resizing-of-playlist](https://user-images.githubusercontent.com/3514015/149633548-d55313cb-0642-46f3-a49e-cb0ab70a0873.gif)

**Comment by vitaly-zdanevich** [comment]
And another freeze - on audio choosing:

![nulloy-freeze-on-audio-choosing](https://user-images.githubusercontent.com/3514015/149634459-8856f6b2-8aa2-40fb-bcfe-2b3f482fd44e.gif)

**Comment by noscript** [comment]
I cannot reproduce it. Is it Sway? Does it happen in i3?

P.S. Please post videos and not gifs in the future. It's not possible to pause it or slow down.

**Comment by vitaly-zdanevich** [comment]
This is on i3.

Ok, will post links to YouTube.

**Comment by noscript** [comment]
Please try running Nulloy with dbg:
```
./configure --debug
make
gdb ./nulloy
(gdb) run
# once Nulloy is frozen, press Ctrl-C
(gdb) backtrace
```

and paste the backtrace here.

> Ok, will post links to YouTube.

No need to upload to YouTube. GitHub supports `.mp4` in comments.

**Comment by vitaly-zdanevich** [comment]
`(No debugging symbols found in ./nulloy)`

**Comment by noscript** [comment]
GStreamer messages are not useful. Please paste the backtrace from GDB.

**Comment by vitaly-zdanevich** [comment]
But after freeze I see a lot of this messages.

**Comment by vitaly-zdanevich** [comment]
...when I just resize the playlist window.

**Comment by vitaly-zdanevich** [comment]
```
(gdb) backtrace 
#0  0x00007ffff637e4ef in write () at /lib64/libc.so.6
#1  0x00007ffff6310805 in _IO_file_write () at /lib64/libc.so.6
#2  0x00007ffff630fba6 in  () at /lib64/libc.so.6
#3  0x00007ffff6310eae in _IO_file_xsputn () at /lib64/libc.so.6
#4  0x00007ffff62fdac7 in  () at /lib64/libc.so.6
#5  0x00007ffff639aa6f in __fprintf_chk () at /lib64/libc.so.6
#6  0x00007ffff5c792b1 in g_log_writer_standard_streams () at /usr/lib64/libglib-2.0.so.0
#7  0x00007ffff5c793c7 in g_log_writer_default () at /usr/lib64/libglib-2.0.so.0
#8  0x00007ffff5c77583 in g_log_structured_array () at /usr/lib64/libglib-2.0.so.0
#9  0x00007ffff5c779d5 in g_log_default_handler () at /usr/lib64/libglib-2.0.so.0
#10 0x00007ffff5c77c2d in g_logv () at /usr/lib64/libglib-2.0.so.0
#11 0x00007ffff5c77f17 in g_log () at /usr/lib64/libglib-2.0.so.0
#12 0x00007ffff482ba57 in gst_bus_timed_pop_filtered () at /usr/lib64/libgstreamer-1.0.so.0
#13 0x00007ffff4b43aeb in  () at /usr/lib64/libgstpbutils-1.0.so.0
#14 0x00007ffff4b440d3 in gst_discoverer_discover_uri () at /usr/lib64/libgstpbutils-1.0.so.0
#15 0x00007ffff4b89e28 in NTagReaderGstreamer::setSource(QString const&) (this=0x555555866cd0, file=...) at tagReaderGstreamer.cpp:79
#16 0x00005555555df242 in NPlaylistWidget::formatItemTitle(NPlaylistWidgetItem*, bool) (this=0x5555558783f0, item=0x555555f96270, force=false)
    at playlistWidget.cpp:308
#17 0x00005555555dd76f in NPlaylistWidget::processVisibleItems() (this=0x5555558783f0) at playlistWidget.cpp:132
#18 0x00005555555ebb29 in NPlaylistWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x5555558783f0, _c=QMetaObject::InvokeMetaMethod, _id=17, _a=0x7fffffffd940) at moc_playlistWidget.cpp:226
#19 0x00007ffff6b086be in  () at /usr/lib64/libQt5Core.so.5
#20 0x00007ffff6b0c90a in QTimer::timeout(QTimer::QPrivateSignal) () at /usr/lib64/libQt5Core.so.5
#21 0x00007ffff6b009ff in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#22 0x00007ffff79196bf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#23 0x00007ffff6ad60a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#24 0x00007ffff6b259c3 in QTimerInfoList::activateTimers() () at /usr/lib64/libQt5Core.so.5
#25 0x00007ffff6b262b9 in  () at /usr/lib64/libQt5Core.so.5
#26 0x00007ffff5c7045c in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#27 0x00007ffff5c70708 in  () at /usr/lib64/libglib-2.0.so.0
#28 0x00007ffff5c707bf in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#29 0x00007ffff6b26678 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#30 0x00007ffff6ad4b3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#31 0x00007ffff6adcee0 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#32 0x00005555555d6c1f in main(int, char**) (argc=1, argv=0x7fffffffe068) at main.cpp:185
```

**Comment by noscript** [comment]
Please try the current master, hopefully 1e4e9d9 fixes the freezing.

**Comment by vitaly-zdanevich** [comment]
Checked, no freeaing now :)

Good to release new version now.
